<div>
    @if ($lesson_id == 1)
        @livewire('lesson.m1l1')
    @elseif ($lesson_id == 2)
        @livewire('lesson.m1l2')
    @elseif ($lesson_id == 3)
        @livewire('lesson.m1l3')
    @elseif ($lesson_id == 4)
        @livewire('lesson.m1l4')
    @elseif ($lesson_id == 5)
        @livewire('lesson.m1l5')
    @elseif ($lesson_id == 6)
        @livewire('lesson.m2l1')
    @elseif ($lesson_id == 7)
        @livewire('lesson.m2l2')
    @elseif ($lesson_id == 8)
        @livewire('lesson.m2l3')
    @elseif ($lesson_id == 9)
        @livewire('lesson.m2l4')
    @elseif ($lesson_id == 10)
        @livewire('lesson.m3l1')
    @elseif ($lesson_id == 11)
        @livewire('lesson.m3l2')
    @endif
</div>
